const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"
const NEW_PRODUCT = "NEW_PRODUCT"
const POST_PRODUCT = "POST_PRODUCT"
const LIKE_PRODUCT = "LIKE_PRODUCT"

module.exports = {
    UPDATE_PRODUCTS,
    NEW_PRODUCT,
    POST_PRODUCT,
    LIKE_PRODUCT
}
